from random import randint
import pprint
#Random names and numbers generated by AI
fl_num = ["SK081", "D82613", "IB824", "BA773", "FR4692", "SK1407", "D84277", "LH2417", "SK883", "OS966"]
cities = ["Visby", "Helsinki", "Madrid", "London LHR", "London STN", "Copenhagen", "Lisbon", "Munich", "Oslo", "Vienna"]
airlines = ["SAS","Norwegian","Iberia","British Airways","Ryanair","SAS","Norwegian","Lufthansa","SAS","Austrian Airlines"]
capacities = [72, 180, 180, 180, 189, 180, 180, 180, 180, 174]
terminals = ["A", "B", "C"]
gates = ["1", "2", "3", "4"]
menu = ["All Departures","Delayed Departures","Cancelled Departures",
        "Search","Statistics","Quit"]
#Function that generates gate combnations
def gate_gen():
    all_gates = []
    for terminal in terminals:
        for gate in gates:
            all_gates.append(terminal+gate)   
    return(all_gates)
all_gates = gate_gen()
#Function that generates a random schedule and returns it sorted by departure times
def generate_schedule(flights, airls, dests, caps, gs):  
    schedule = []
    for i in range(len(flights)):
        hour = randint(0,23)
        minute = randint(0,59)
        cancelation = False
        delay = 0
        if randint(0,100) >= 80:
            delay = randint(0,70)
        temp = {
            "Flight Number" : flights[i],
            "Airline" : airls[i],
            "Destination" : dests[i],
            "Departure Time" : f"{hour:02d}:{minute:02d}",
            "Gate" : gs[i],
            "Passengers" : randint(0, caps[i]),
            "Maximum Capacity" : caps[i],
            "Delay" : delay,
            "Cancelation Status" : cancelation
        }
        schedule.append(temp)
    schedule[randint(0,len(schedule)-1)]["Cancelation Status"] = True
    schedule[randint(0,len(schedule)-1)]["Gate"] = "Gate not assigned"
    schedule[randint(0,len(schedule)-1)]["Passengers"] = 0

    return sorted(schedule, key=lambda x: x["Departure Time"])
new_schedule = generate_schedule(fl_num,airlines,cities,capacities,all_gates)

pprint.pprint(new_schedule, indent=4, width=60)
print("Welcome to Flight Control!")
print("To navigate, input the number of the function.")
active = True
while active == True:
    pprint.pprint(list(enumerate(menu, start=1)), indent=4, width=60)
    choice = int(input("Type the number of the operation to proceed:"))
    match choice:
        case 1:
            for schedule in new_schedule:
                if schedule['Cancelation Status']:
                    print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - CANCELLED")
                else:
                    if schedule['Delay'] == 0:
                        print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - ON TIME")
                    elif schedule['Delay'] > 0 and schedule['Delay'] < 20:
                        print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - SLIGHT DELAY")
                    elif schedule['Delay'] >= 20 and schedule['Delay'] < 60:
                        print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - DELAYED")
                    else:
                        print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - SEVERLY DELAYED")
        case 2:
            for schedule in new_schedule:
                if schedule['Delay'] > 0:
                    print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - DELAYED BY " + str(schedule['Delay']) + " minutes.")
        case 3:
            for schedule in new_schedule:
                if schedule['Cancelation Status']:
                    print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'] + " - CANCELLED")
        case 4:
            flight = input("Type the flight number you wish to search for:").strip().upper()
            
            for schedule in new_schedule:
                if schedule['Flight Number'] == flight:
                    print(schedule['Flight Number'] + " - " + schedule['Destination'] + " - " + schedule['Departure Time'] + " - " + schedule['Gate'])
                    break
            else:
                print("Flight not found!")
        case 5:
            stats = [0, 0, 0, 0, 0, 0, 0, 0, 0]
            for schedule in new_schedule:
                stats[0] += 1 #Total scheduled flights
                if schedule['Cancelation Status']:
                    stats[1] += 1 #Canceled flights
                elif schedule['Delay'] > 0:
                    stats[2] += 1 #Delayed flight
                else:
                    stats[3] += 1 #Flights on time
                if schedule['Passengers'] > 0:
                    stats[4] += schedule['Passengers'] # Total number of passengers
                    stats[5] += 1 #Active flights
                if schedule['Passengers'] > stats[7]:
                    stats[6] = schedule['Flight Number'] #Flight with most passengers
                    stats[7] = schedule['Passengers'] #Number of passengers
                if schedule['Passengers'] / schedule['Maximum Capacity'] > 0.8:
                    stats[8] += 1 #Number of flights with 80% or more booked seats
                
            print(f"""
            Scheduled flights: {stats[0]},
            Canceled flights: {stats[1]},
            Delayed flights: {stats[2]},
            On-time: {stats[3]},
            
            Passengers today: {stats[4]},
            Average number of passengers per flight: {stats[4]/stats[5]},
            Busiest flight: {stats[6]} - {stats[7]} passengers,
            Number of flights with more than 80% of their capacity filled: {stats[8]},
            Active Gates: {all_gates}
            """)            
        case 6:
            break
        case _:
            print("Invalid imput! Please type a digit!")
    