from random import randint
import pprint
#Random names and numbers generated by AI
fl_num = ["SK081", "D82613", "IB824", "BA773", "FR4692", "SK1407", "D84277", "LH2417", "SK883", "OS966"]
cities = ["Visby", "Helsinki", "Madrid", "London LHR", "London STN", "Copenhagen", "Lisbon", "Munich", "Oslo", "Vienna"]
airlines = ["SAS","Norwegian","Iberia","British Airways","Ryanair","SAS","Norwegian","Lufthansa","SAS","Austrian Airlines"]
capacities = [72, 180, 180, 180, 189, 180, 180, 180, 180, 174]
terminals = ["A", "B", "C"]
gates = ["1", "2", "3", "4"]
#Function that generates a random schedule and returns it sorted by departure times
def generate_schedule(flights, airls, dests, caps, terms, gs):
    all_gates = []
    for terminal in terms:
        for gate in gs:
            all_gates.append(terminal+gate)
    schedule = []
    
    for i in range(len(flights)):
        hour = randint(0,23)
        minute = randint(0,60)
        cancelation = False
        if randint(0,100) >= 90:
            cancelation = True
        temp = {
            "Flight Number" : flights[i],
            "Airline" : airls[i],
            "Destination" : dests[i],
            "Departure Time" : f"{hour:02d}:{minute:02d}",
            "Gate" : all_gates[i],
            "Passengers" : randint(0, caps[i]),
            "Maximum Capacity" : caps[i],
            "Delay" : randint(0,70),
            "Cancelation Status" : cancelation
        }
        schedule.append(temp)
    return sorted(schedule, key=lambda x: x["Departure Time"])
new_schedule = generate_schedule(fl_num,airlines,cities,capacities,terminals,gates)
pprint.pprint(new_schedule, indent=4, width=60)